"""Isolated infrastructure for reproducible reference comparisons."""

from seedvision.benchmarking.checkpoints import (
    CHECKPOINT_FORMAT,
    CHECKPOINT_VERSION,
    MAX_ARRAY_BYTES,
    MAX_ARRAYS,
    MAX_CHECKPOINT_BYTES,
    BenchmarkCheckpoint,
    CheckpointCancelled,
    CheckpointError,
    CheckpointIdentity,
    CheckpointLimits,
    CheckpointMismatch,
    CheckpointReference,
    CoordinateFrame,
    ExecutionRecord,
    ExecutionStatus,
    InvalidCheckpoint,
    MeasurementContract,
    RasterRole,
    load_checkpoint,
    load_stage_input,
    publish_checkpoint,
)

__all__ = [
    "CHECKPOINT_FORMAT",
    "CHECKPOINT_VERSION",
    "MAX_ARRAY_BYTES",
    "MAX_ARRAYS",
    "MAX_CHECKPOINT_BYTES",
    "BenchmarkCheckpoint",
    "CheckpointCancelled",
    "CheckpointError",
    "CheckpointIdentity",
    "CheckpointLimits",
    "CheckpointMismatch",
    "CheckpointReference",
    "CoordinateFrame",
    "ExecutionRecord",
    "ExecutionStatus",
    "InvalidCheckpoint",
    "MeasurementContract",
    "RasterRole",
    "load_checkpoint",
    "load_stage_input",
    "publish_checkpoint",
]
