"""Generate the current operator-facing node/optimization catalogue from code."""
from pathlib import Path
import argparse
import sys
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from seedvision.pipeline import build_default_pipeline
from seedvision.optimization.registry import capability


def render():
    lines = ['# Current node catalogue','',
        'Generated by `python scripts/generate_node_catalogue.py`; do not edit by hand.',
        'Optimization is image-local adaptation, not independent validation. Physical facts and scoring policies remain fixed.','']
    graph = build_default_pipeline()
    for identifier,node in graph.nodes.items():
        disposition = capability(node)
        lines.extend([f'## {node.title} (`{identifier}`)','',node.description,'',
            f'Optimization: {disposition.reason or disposition.objective}.','',
            '| Control | Default | Search status |','|---|---|---|'])
        fixed = dict(disposition.fixed)
        for spec in node.parameter_specs:
            value = str(node.parameters[spec.key]).replace('|','\\|')
            lines.append(f'| {spec.label} (`{spec.key}`) | {value} | {fixed.get(spec.key,"Eligible when reviewed targets are available")} |')
        lines.append('')
    return '\n'.join(lines)+'\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args = parser.parse_args()
    target = ROOT/'docs'/'NODE_CATALOGUE.md'
    expected = render()
    if args.check:
        if not target.exists() or target.read_text(encoding='utf-8') != expected:
            raise SystemExit('Node catalogue is stale; regenerate it.')
    else:
        target.write_text(expected,encoding='utf-8')
